using YoutubeAPI.Models.ValueTypes;

namespace YoutubeAPI.Models.Videos;

/// <summary>
///     Represents a transcript or closed-caption track available for a video.
/// </summary>
/// <param name="Id">The unique identifier of the transcript track.</param>
/// <param name="LanguageCode">The BCP-47 or ISO language code (e.g. "en", "es").</param>
/// <param name="DisplayName">The user-visible display name of the track.</param>
/// <param name="IsAutoGenerated">Whether the transcript was automatically generated by speech recognition.</param>
public sealed record TranscriptTrack(
    TranscriptTrackId Id,
    string LanguageCode,
    string DisplayName,
    bool IsAutoGenerated);