using System.Net;
using System.Text;
using Xunit;
using YoutubeAPI.Exceptions;

namespace YoutubeAPI.Tests.Authentication;

public sealed class CookieAuthenticationTests
{
    [Fact]
    public void FromCookiesWithValidCookiesClonesCookiesAndPreservesProperties()
    {
        var originalCookie = new Cookie("SAPISID", "test_sapisid_value", "/", ".youtube.com")
        {
            Secure = true,
            HttpOnly = true,
            Expires = DateTime.UtcNow.AddHours(2),
            Comment = "test comment",
            Discard = false,
            Version = 1
        };

        var auth = YouTubeCookieAuthentication.FromCookies([originalCookie]);

        Assert.Single(auth.Cookies);
        var cloned = auth.Cookies[0];
        Assert.Equal("SAPISID", cloned.Name);
        Assert.Equal("test_sapisid_value", cloned.Value);
        Assert.Equal("/", cloned.Path);
        Assert.Equal(".youtube.com", cloned.Domain);
        Assert.True(cloned.Secure);
        Assert.True(cloned.HttpOnly);
        Assert.Equal(originalCookie.Expires, cloned.Expires);
        Assert.Equal("test comment", cloned.Comment);
        Assert.Equal(1, cloned.Version);

        // Verify clone isolation: mutating original doesn't affect auth
        originalCookie.Value = "mutated_value";
        Assert.Equal("test_sapisid_value", auth.Cookies[0].Value);
    }

    [Fact]
    public void FromCookiesWithNullCollectionThrowsArgumentNullException()
    {
        Assert.Throws<ArgumentNullException>(() => YouTubeCookieAuthentication.FromCookies(null!));
    }

    [Fact]
    public void FromCookiesWithNullEntriesAndExpiredCookiesSkipsThem()
    {
        var validCookie = new Cookie("SAPISID", "valid_token", "/", ".youtube.com")
        {
            Expires = DateTime.UtcNow.AddDays(1)
        };
        var expiredCookie = new Cookie("EXPIRED", "expired_token", "/", ".youtube.com")
        {
            Expires = DateTime.UtcNow.AddDays(-1)
        };

        var cookies = new List<Cookie?> { null, validCookie, expiredCookie, null };
        var auth = YouTubeCookieAuthentication.FromCookies(cookies);

        Assert.Single(auth.Cookies);
        Assert.Equal("SAPISID", auth.Cookies[0].Name);
    }

    [Fact]
    public void FromNetscapeWithHttpOnlyPrefixParsesAndSetsHttpOnlyFlag()
    {
        var futureExpiry = DateTimeOffset.UtcNow.AddDays(30).ToUnixTimeSeconds();
        var netscapeContent = $"#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t{futureExpiry}\tHSID\thttp_only_secret\n";

        var auth = YouTubeCookieAuthentication.FromNetscape(netscapeContent);

        Assert.Single(auth.Cookies);
        var cookie = auth.Cookies[0];
        Assert.Equal("HSID", cookie.Name);
        Assert.Equal("http_only_secret", cookie.Value);
        Assert.Equal(".youtube.com", cookie.Domain);
        Assert.Equal("/", cookie.Path);
        Assert.True(cookie.Secure);
        Assert.True(cookie.HttpOnly);
    }

    [Fact]
    public void FromNetscapeWithCommentsAndBlankLinesIgnoresThem()
    {
        var futureExpiry = DateTimeOffset.UtcNow.AddDays(30).ToUnixTimeSeconds();
        var netscapeContent = $"""
                               # Netscape HTTP Cookie File
                               # http://curl.haxx.se/rfc/cookie_spec.html
                               # This file was generated by an export tool

                               .youtube.com	TRUE	/	TRUE	{futureExpiry}	SAPISID	valid_sapisid

                               # Another comment
                                  
                               .youtube.com	TRUE	/	TRUE	{futureExpiry}	SSID	valid_ssid
                               """;

        var auth = YouTubeCookieAuthentication.FromNetscape(netscapeContent);

        Assert.Equal(2, auth.Cookies.Count);
        Assert.Equal("SAPISID", auth.Cookies[0].Name);
        Assert.Equal("SSID", auth.Cookies[1].Name);
    }

    [Fact]
    public void FromNetscapeWithSessionAndExpiredCookiesFiltersExpiredOnly()
    {
        var pastExpiry = DateTimeOffset.UtcNow.AddDays(-5).ToUnixTimeSeconds();
        var futureExpiry = DateTimeOffset.UtcNow.AddDays(5).ToUnixTimeSeconds();

        var netscapeContent = $"""
                               .youtube.com	TRUE	/	TRUE	0	SESSION_COOKIE	session_val
                               .youtube.com	TRUE	/	TRUE	{pastExpiry}	EXPIRED_COOKIE	expired_val
                               .youtube.com	TRUE	/	TRUE	{futureExpiry}	FUTURE_COOKIE	future_val
                               """;

        var auth = YouTubeCookieAuthentication.FromNetscape(netscapeContent);

        Assert.Equal(2, auth.Cookies.Count);
        Assert.Contains(auth.Cookies, c => c.Name == "SESSION_COOKIE");
        Assert.Contains(auth.Cookies, c => c.Name == "FUTURE_COOKIE");
        Assert.DoesNotContain(auth.Cookies, c => c.Name == "EXPIRED_COOKIE");
    }

    [Fact]
    public void FromNetscapeWithMalformedLineThrowsFormatExceptionWithLineNumber()
    {
        const string netscapeContent = """
                                       # Line 1: Comment
                                       .youtube.com	TRUE	/	TRUE	1999999999	COOKIE1	VAL1
                                       .youtube.com	INCOMPLETE_ROW
                                       .youtube.com	TRUE	/	TRUE	1999999999	COOKIE3	VAL3
                                       """;

        var ex = Assert.Throws<FormatException>(() => YouTubeCookieAuthentication.FromNetscape(netscapeContent));
        Assert.Contains("line 3", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void FromNetscapeWithMalformedExpiryThrowsFormatExceptionWithLineNumber()
    {
        const string netscapeContent = """
                                       # Line 1: Comment
                                       .youtube.com	TRUE	/	TRUE	not_a_number	COOKIE1	VAL1
                                       """;

        var ex = Assert.Throws<FormatException>(() => YouTubeCookieAuthentication.FromNetscape(netscapeContent));
        Assert.Contains("line 2", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void FromNetscapeStreamOverloadReadsEagerlyAndMatchesStringOverload()
    {
        var futureExpiry = DateTimeOffset.UtcNow.AddDays(10).ToUnixTimeSeconds();
        var netscapeContent = $".youtube.com\tTRUE\t/\tTRUE\t{futureExpiry}\tSAPISID\tsapisid_from_stream\n";

        using var memoryStream = new MemoryStream(Encoding.UTF8.GetBytes(netscapeContent));
        var authFromStream = YouTubeCookieAuthentication.FromNetscape(memoryStream);
        var authFromString = YouTubeCookieAuthentication.FromNetscape(netscapeContent);

        Assert.Single(authFromStream.Cookies);
        Assert.Equal(authFromString.Cookies[0].Name, authFromStream.Cookies[0].Name);
        Assert.Equal(authFromString.Cookies[0].Value, authFromStream.Cookies[0].Value);

        // Verify stream wasn't closed if leaveOpen was desired
        Assert.True(memoryStream.CanRead);
    }

    [Fact]
    public void FromNetscapeWithNullThrowsArgumentNullException()
    {
        Assert.Throws<ArgumentNullException>(() => YouTubeCookieAuthentication.FromNetscape((string)null!));
        Assert.Throws<ArgumentNullException>(() => YouTubeCookieAuthentication.FromNetscape((Stream)null!));
    }

    [Fact]
    public void ToStringRedactsSecrets()
    {
        var futureExpiry = DateTimeOffset.UtcNow.AddDays(10).ToUnixTimeSeconds();
        var netscapeContent = $".youtube.com\tTRUE\t/\tTRUE\t{futureExpiry}\tSAPISID\tsuper_secret_token_value\n";

        var auth = YouTubeCookieAuthentication.FromNetscape(netscapeContent);
        var result = auth.ToString();

        Assert.Equal("[Redacted]", result);
        Assert.DoesNotContain("super_secret_token_value", result);
        Assert.DoesNotContain("SAPISID", result);
    }

    [Fact]
    public void SapisidPropertiesExtractsExpectedTokens()
    {
        var futureExpiry = DateTimeOffset.UtcNow.AddDays(10).ToUnixTimeSeconds();

        // 1. With SAPISID
        var withSapisid = $".youtube.com\tTRUE\t/\tTRUE\t{futureExpiry}\tSAPISID\tsapisid_token_123\n";
        var auth1 = YouTubeCookieAuthentication.FromNetscape(withSapisid);
        Assert.Equal("sapisid_token_123", auth1.Sapisid);
        Assert.Null(auth1.Secure3Papisid);
        Assert.Equal("sapisid_token_123", auth1.GetSapisidOrSecure());
        Assert.Equal("sapisid_token_123", auth1.GetRequiredSapisid());

        // 2. With __Secure-3PAPISID only
        var with3Papisid = $".youtube.com\tTRUE\t/\tTRUE\t{futureExpiry}\t__Secure-3PAPISID\tsecure_3p_token_456\n";
        var auth2 = YouTubeCookieAuthentication.FromNetscape(with3Papisid);
        Assert.Null(auth2.Sapisid);
        Assert.Equal("secure_3p_token_456", auth2.Secure3Papisid);
        Assert.Equal("secure_3p_token_456", auth2.GetSapisidOrSecure());
        Assert.Equal("secure_3p_token_456", auth2.GetRequiredSapisid());

        // 3. Without SAPISID or __Secure-3PAPISID
        var otherCookies = $".youtube.com\tTRUE\t/\tTRUE\t{futureExpiry}\tOTHER_COOKIE\tother_val\n";
        var auth3 = YouTubeCookieAuthentication.FromNetscape(otherCookies);
        Assert.Null(auth3.Sapisid);
        Assert.Null(auth3.Secure3Papisid);
        Assert.Null(auth3.GetSapisidOrSecure());
        Assert.Throws<AuthenticationRequiredException>(auth3.GetRequiredSapisid);
    }
}