<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <PackageId>YoutubeAPI</PackageId>
        <PackageLicenseExpression>LGPL-3.0</PackageLicenseExpression>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <IsAotCompatible>true</IsAotCompatible>
        <IsTrimmable>true</IsTrimmable>
        <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
        <EnableSingleFileAnalyzer>true</EnableSingleFileAnalyzer>
        <EnableAotAnalyzer>true</EnableAotAnalyzer>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="YoutubeExplode"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="YoutubeAPI.Tests"/>
        <InternalsVisibleTo Include="YoutubeAPI.LiveTests"/>
    </ItemGroup>

</Project>
